### ISSUE TITLE
App breaking

### ISSUE THREAD

**Issue by shashankd96** [direwolf424/Lanify#16] opened 2016-07-31 16:15 UTC
Check app for song Dont Let Me Down. Page reloading when trying to play. Therefore adding UK TOP 40 to the playlist using play option is also crashing.

**Comment by direwolf424** [comment] 2016-07-31 17:50
Due to quotation marks present in the json we are facing this problem 
Duplicate of #14

**Closed as completed** 2016-08-09 17:06 UTC
Labels: bug, duplicate
